### PR TITLE
add cron + remove not needed part in docker-compose

### PR DESCRIPTION
**Pull request by thib3113**
Hello, 

I've add cron for seopanel, and remove not needed parts in the docker-compose

### CODE REVIEW

**Comment by thib3113** [comment]
Hum, oh, I push my tests on prepare-config.sh .... Sorry, in facts it's change nothing :/ ( just use same shebang as run.sh, and absolute path )

**Comment by Mike-Petersen** [comment]
Hi,
thanks for the contribution.

Normally in docker only one process runs. So the cron would not be executed in the container or am i missing something?

**Comment by thib3113** [comment]
Hum, I've some doubts now .... I'll try :/ ...

**Comment by thib3113** [comment]
Hum, so, after some research, it seems supervisord seems to be a good way . 

So, I've done some tests, and push the image ( so docker will built it, and I can do more tests ) . I'll check tomorrow if it's work or not (for my test, crontest call 127.0.0.1, so write an entry in log, this work each minutes).

**Comment by Mike-Petersen** [comment]
There is one downside with using tools like supervisord or runit. If a process fails only supervisord/runit will know about it.

In my opinion the best would be to use two containers. One running the seopanel and one for the cron. That could be managed by an environment variable. So if the environment variable does not exist, it runs seopanel, otherwise cron.

**Comment by thib3113** [comment]
Hum, why ?

For the moment, for my tests,  supervisord is managed like that: 
`[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log;
pidfile=/var/run/supervisord.pid;
loglevel=debug

[program:cron]
command = cron -f
redirect_stderr=true
redirect_stdout=true

[program:apache]
command = /run.sh
redirect_stdout=true
redirect_stderr=true`

So, the stdout show all the apache access logs, and maybe errors logs like : 
`2018-02-27 13:31:01,497 DEBG 'apache' stdout output:
127.0.0.1 - - [27/Feb/2018:13:31:01 +0000] "GET / HTTP/1.0" 200 15074 "-" "-"

2018-02-27 13:32:01,548 DEBG 'apache' stdout output:
127.0.0.1 - - [27/Feb/2018:13:32:01 +0000] "GET / HTTP/1.0" 200 15074 "-" "-"`
( yes to test I've created a file calling http://127.0.0.1, to add entries in apache log ) .

For cron, I don't have any output for the moment, so, my idea is to redirect cron ouptut to /var/log/cron.log, and adding a task "tail -f" .

But for the moment, I've some problems with the cron.php file, because it doesn't support to be called from another position ( like if you call cron.php from /, the php file can't found some files to include .... ), so I'll continue my tests on this .


About your idea of the two containers, you want to do somethings like : 
 - one with seopanel to manage apache
 - one with seopanel to manage cron 
Connected to the same database and/or the same files ? In my opinion, this is maybe too big ? no ? A complete container only for a cron ? and so, you need 3 containers only for seopanel :/ ... I think it's not really easy .

But, I'm really not an expert in Docker, I learn by tests, so, it's maybe the better solution :) .

**Comment by thib3113** [comment]
Ok, so finally, after long searches, it's work ... Maybe not the best way, but it's work .

On the stdout you get the apache stdout, and the cron ( with cron.log ) . 

Maybe missing some part coming from apache error.log, need to do some tests on this . 

For the moment, I'll try on a real platform ( real linux + real data, insteed of docker toolbox on windows + empty database )

**Comment by Mike-Petersen** [comment]
Because with additional programs like supervisord you add more complexity. With just using docker and one process all you need to do is monitor docker containers. With supervisord or anything like that monitoring only the docker containers is not enough.

E.g. if you simply monitor docker containers without supervisord on any program failure you will get the info. But with supervisord the docker container will still be running. So you would need to monitor the processes in the docker container too.

Sometimes the easiest is the best solution. Running docker containers does not produce a lot of overhead. So running a second one is easy.

**Pull request closed without merging**
